/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 furniture2.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('/furniture2.glb')
  return (
    <group {...props} dispose={null} rotation={[0.2,170,0.2]} scale={0.8}>

      <mesh geometry={nodes.Circle005.geometry} material={materials['02 - VRay Material']} rotation={[-Math.PI, -Math.PI / 1, 0]} scale={12} position={[0, -2, 0]}/>

      <mesh geometry={nodes.Cylinder003.geometry} material={materials['derevo star.saltov']} rotation={[0, 0, 0]} 
      position={[0, -2.1, 0]} scale={12} />
    </group>
  )
}

useGLTF.preload('/furniture2.glb')
